### ISSUE TITLE
Get the API multiaddr through the api file

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfsd-ctl#108]
This https://github.com/ipfs/js-ipfsd-ctl/pull/107#r79108143 is currently really hacky

**Comment by haadcode** [comment]
Related, I added the gateway address so that when daemon is bound to `.../tcp/0`, we get the gateway address back: https://github.com/haadcode/js-ipfsd-ctl/commit/257712108919a05c625b02399b82d873675bc559. @diasdavid want me to PR this?

**Comment by diasdavid** [comment]
please do :)

**Comment by diasdavid** [comment]
@haadcode I'll take your `haadcode removed their assignment on 17 Jan` as no follow up for this issue. Closing then :)
