### ISSUE TITLE
Fragmentation

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfsd-ctl#136]
TIL that there is a [@haad/ipfsd-ctl](https://www.npmjs.com/package/@haad/ipfsd-ctl). I don't understand why there is a need to create such a module, but it seems it has been going for a while, making it more than an experiment, but an actual fork/module available in NPM.

I very much disagree with this approach because it is clearly fragmenting the ecosystem set by creating yet another module that is _not being tracked as a PR_ and doesn't show any future where that will happen, making us maintain 2 modules instead of one.

When the challenge on https://github.com/ipfs/js-ipfs/issues/556 was launched, the proposal was exactly to reduce fragmentation and to make the launch of IPFS nodes more easily, but what I see that got created was another module, [ipfs-daemon](https://github.com/haadcode/ipfs-daemon), which has its [set of issues](https://github.com/haadcode/ipfs-daemon/issues/7), which uses a module that is a fork of this one, namely [@haad/ipfsd-ctl](https://www.npmjs.com/package/@haad/ipfsd-ctl).

@haadcode can we converge all of these, it really doesn't help. Others are invited to provide their feedback, I might also be missing the value and apologize in advance if I'm doing so.

**Comment by diasdavid** [comment]
We can see on how one is getting behind
![image](https://cloud.githubusercontent.com/assets/1211152/21124325/1adbd728-c093-11e6-9957-c4b387bbae09.png)

**Comment by diasdavid** [comment]
Found this one too https://github.com/haadcode/ipfs-test-apis

**Comment by diasdavid** [comment]
@haadcode we need to converge https://github.com/haadcode/js-ipfsd-ctl into this. What are the steps for that? What is stopping you from using the main one and maintaining a fork?

**Comment by haadcode** [comment]
Short: 0.4.5.

Long:
The fork was originally done to have 0.4.5 go-ipfs bin in the chain of deps for Orbit (which needed pubsub). 

So, to unravel all that, we need to merge https://github.com/ipfs/npm-go-ipfs-dep/pull/18 and https://github.com/ipfs/npm-go-ipfs-dep/pull/19 and release `go-ipfs-dep@0.4.5`. 

The other part is to merge https://github.com/ipfs/js-ipfsd-ctl/pull/145 and release new version of `ipfsd-ctl` (this PR will make `ipfs-daemon` compatible with `js-ipfsd-ctl`). And after releasing 0.4.5 we should release `ipfsd-ctl` with the new `go-ipfs-dep` version.

That's all! :) Finally there 🎉 🎆

**Comment by diasdavid** [comment]
- [x] https://github.com/ipfs/npm-go-ipfs-dep/pull/18 
- [x] https://github.com/ipfs/npm-go-ipfs-dep/pull/19 
- [x] go-ipfs-dep@0.4.5
- [ ] https://github.com/ipfs/js-ipfsd-ctl/pull/145

I see a breaking change proposed on https://github.com/ipfs/js-ipfsd-ctl/pull/145 and no PRs to js-ipfs and js-ipfs-api that cope with that change, meaning that the poor soul that merges and releases would have to run and put up fires. Can we avoid this by preemptively having PRs that cope with the fixes so that no one is caught off guard?

**Comment by diasdavid** [comment]
All done \o/
