### ISSUE TITLE
Doesn't kill daemon / sub-process

### ISSUE THREAD

**Issue by haadcode** [ipfs/js-ipfsd-ctl#143]
Previously, js-ipfsd-ctl killed all sub-processes upon process exit. However, with the recent refactoring, that doesn't seem to be the case anymore :/

If you run the tests, for example only the 'start daemon' ones (describe.only('startDaemon')), the tests will pass but if you then do `ps -A|grep ipfs` you will see that there are still ipfs processes running (3 if I counted correctly). I'm on OSX, running js-ipfsd-ctl from master.

This is a **major** issue.

@jbenet kept trying to say that this is exactly what we need to avoid, because the old code was crafted over time to handle this exact case. We need to put fixing this on highest priority because it basically effects every program that uses js-ipfsd-ctl, leaving processes hanging.

cc @dignifiedquire @diasdavid @VictorBjelkholm

**Comment by dignifiedquire** [comment]
This is strange, because we didn't actually change the spawning, I reverted those changes and we still use `subcomandante` for the exiting.

**Comment by haadcode** [comment]
Could we try to verify this on various platforms? Can you reproduce it locally? Can we reproduce it on CI?

**Comment by diasdavid** [comment]
I'm seeing this error two, but here is further debugging:

- The test `SIGKILL kills survivor` just hangs, leaving a couple of ipfs processes running. 
- Skipping the previous tests makes everything pass
- Running the tests again will make `1) start and stop` fail with:

```sh
 1) daemons startDaemon start and stop:
     Error: Error: ipfs configuration file already exists!
Reinitializing would overwrite your keys.


      at Object.done (src/exec.js:22:27)
      at Stream.listeners.done.once (src/exec.js:44:18)
      at Stream.f (node_modules/once/once.js:25:25)
      at Socket.reemit (node_modules/duplexer/index.js:70:25)
      at Pipe._handle.close [as _onclose] (net.js:498:12)
```

**Comment by diasdavid** [comment]
@haadcode it was `is-running` https://github.com/ipfs/js-ipfsd-ctl/pull/144

**Comment by diasdavid** [comment]
fix on https://github.com/ipfs/js-ipfsd-ctl/pull/144
