### ISSUE TITLE
(go-ipfs 0.4.5-pre1) Error: ipfs configuration file already exists!

### ISSUE THREAD

**Issue by haadcode** [ipfs/js-ipfsd-ctl#146]
Running the tests with go-ipfs 0.4.5-pre1 binary, the following error gets thrown:
```
     Error: non-zero exit code 1

            while running: /Users/haad/code/js-ipfsd-ctl-github/node_modules/go-ipfs-dep/go-ipfs/ipfs init -b 2048


            Error: ipfs configuration file already exists!
Reinitializing would overwrite your keys.
```

I believe something was changed in 0.4.5 re how the init is handled (this is what I was trying to explain on IRC the other day). @whyrusleeping @Kubuxu would you be able to tell us what was changed? Was '--force' removed? Is this behaviour intentional?

If this is intentional, I wonder how we should handle / fix it...

(With 0.4.4 the tests pass)

cc @ipfs/javascript-team

**Comment by whyrusleeping** [comment]
the `init --force` option was removed quite some time ago, you should make sure to clean up daemons between reinitialization

**Comment by haadcode** [comment]
Figured it out, this was a problem with module paths on my side. Closing as invalid.
