### ISSUE TITLE
node hangs does not exit after ipfsd.disposableApi

### ISSUE THREAD

**Issue by thisconnect** [ipfs/js-ipfsd-ctl#148]
running this example https://github.com/ipfs/js-ipfsd-ctl/blob/master/example.js  does log the id, publicKey etc. but the Node.js process never ends

```
node --version
v6.10.0
npm --version
3.10.10

ipfsd-ctl@0.19.0

```

**Comment by diasdavid** [comment]
That's on purpose, the daemon is spawn in a child process that you are never stopping, so the parent process won't stop too.

To close the process graciously, you will need to call the stopDaemon method: https://github.com/ipfs/js-ipfsd-ctl/blob/master/src/node.js#L243-L259

**Comment by thisconnect** [comment]
I assumed this would happen as the comment states:

> // Start a disposable node, and get access to the api
> // print the node id, and kill the temporary daemon

https://github.com/ipfs/js-ipfsd-ctl/blob/master/example.js#L4

Would you accept a PR that adds stopDaemon to the example?

**Comment by diasdavid** [comment]
@thisconnect absolutely, thank you :)

**Comment by thisconnect** [comment]
Another minor find using disposableApi or disposable:

When there was an error, the tmp dir is not removed.
It's all good when **no** error occurred (tmp is properly rimraf'd).

Do you consider this a bug, if yes should I open an issue?

**Comment by diasdavid** [comment]
It can be considered a bug, although tmp folder is cleaned by the OS. Understand that is annoying and it can double checked to be fixed

**Comment by thisconnect** [comment]
Not sure if you have seen my second last comment but I am stuck, https://github.com/ipfs/js-ipfsd-ctl/issues/148#issuecomment-292207513

**Comment by diasdavid** [comment]
@thisconnect sounds like you just have to propagate those functions to the API object so that they are exposed through what is returned on the disposableApi call

**Comment by diasdavid** [comment]
@thisconnect got my message?

**Comment by thisconnect** [comment]
disposableApi currently returns (err, api)

are you saying I should open a PR, that it returns (err, api+stopDaemon)?

**Comment by thisconnect** [comment]
The docs say nothing about that the process should end automatically https://ipfs.github.io/js-ipfsd-ctl/#ipfsdaemoncontrollerdisposableapi

So I just removed the comment that confused me https://github.com/ipfs/js-ipfsd-ctl/pull/154 for now
