### ISSUE TITLE
Future of ipfd-ctl (for consideration)

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfsd-ctl#149]
Taken from: https://github.com/ipfs/js-ipfs/issues/556#issuecomment-286494980

----------------

Satelite modules ipfsd-ctl vs ipfs-daemon vs ipfs-factory

We need a thing that lets us spawn nodes (js-ipfs and go-ipfs) easily, so that apps like orbit, our tests and benchmarks can switch between different combinations (js-ipfs, js-ipfs daemon + js-ipfs-api, go-ipfs + js-ipfs-api) without too much configuration.

This endeavor doesn't have to be part of "Improving Init", but it would be definitely useful to a lot of contributors, users and even for our testing.

Currently, we have:

ipfsd-ctl - spawns go-ipfs daemons and returns a js-ipfs-api instance to talk with them
ipfs-factory (not a module, just a tool within this repo) - spawns daemons from Node.js and the Browser.
ipfs-daemon - https://github.com/haadcode/ipfs-daemon
ipfsd-ctl is the one that has more adoption.

**Comment by thisconnect** [comment]
Can this be closed?

**Comment by diasdavid** [comment]
Sure :) It's not urgent anymore
