### ISSUE TITLE
BUG: getConfig should return the whole config

### ISSUE THREAD

**Issue by thisconnect** [ipfs/js-ipfsd-ctl#152]
If no key is passed, the whole config is returned as an object.

https://ipfs.github.io/js-ipfsd-ctl/#nodegetconfig

currently it returns Error: Failed to get config value: " key has no attributes"

see https://github.com/ipfs/js-ipfsd-ctl/pull/151

**Comment by thisconnect** [comment]
Another test fails on Node 6 https://travis-ci.org/ipfs/js-ipfsd-ctl/builds/244451297

**Comment by thisconnect** [comment]
After reopening the PR, the other test now fails on Node 4 https://travis-ci.org/ipfs/js-ipfsd-ctl/builds/245233174

**Comment by diasdavid** [comment]
Thank you for fixing the config bit. Let's review the remaining bugs in another issue/PR

**Comment by thisconnect** [comment]
Sure, not sure what it could be but I opened for the random CI failures https://github.com/ipfs/js-ipfsd-ctl/issues/158
