### ISSUE TITLE
Detect if ipfs daemon is already running.

### ISSUE THREAD

**Issue by paulogr** [ipfs/js-ipfsd-ctl#175]
Is there a way to detect if the ipfs daemon is already running?

thanks!

**Comment by dryajov** [comment]
It depends

- If using the `.disposable` method, it will only give you a node which has to be explicitly started/stopped - you'll have to start it yourself with `ipfs.startNode()`
- if using `.disposableApi` method you'll get the node started and an instance of `ipfs-api` connected to that node

Both of this methods take an explicit repo path, if an instance is already running using that repo, the new daemon will fail acquiring the repo lock - this should be a good indicative of whether there is a daemon running or not.

What is your particular use case?

**Comment by paulogr** [comment]
Thank you for your answer!

I'm using the `.local` method and, to tell the truthy I'm still have difficult to understand the difference between those three methods.

So far I understand the `.local` method I get an ipfs node and start it myself like you sad it works with `.disposable` method. But I don't want the repo gets removed after I stop the service.

I'm building a node js app, and getting problems to catch this error because it doesn't have a **code** or any indicative that was caused by an already running deamon. There is no way to distinguish this error from another critical error.

Do you know what I mean?

**Comment by diasdavid** [comment]
ref: #182

**Comment by dryajov** [comment]
This has been addressed in https://github.com/ipfs/js-ipfsd-ctl/pull/221
