### ISSUE TITLE
Connect to already running daemon

### ISSUE THREAD

**Issue by hacdias** [ipfs/js-ipfsd-ctl#182]
After talking to @dryajov, we noticed that `ipfsd-ctl` doesn't connect to already running daemons. This code:

```
DaemonFactory.create().spawn({
  repoPath: "/a/beautiful/path",
  disposable: false,
  init: false,
  start: false
}, (err, node) => { console.log(node.started) })
```

Should print `true` if the there was a daemon on that repo and `node.api` should be populated. 😄

**Comment by diasdavid** [comment]
@hacdias this is only on the latest version that hasn't been merged right? Namely #176 ? Was this a feature that you use in the current released version? If so it is a regression and #176 shouldn't be merged until it is fixed.

@hacdias can you add a test for it on the PR?

**Comment by hacdias** [comment]
@diasdavid I don't know if the current version can connect to already running daemons. I have tried but it didn't seem to work neither with master, nor with #176

**Comment by dryajov** [comment]
@diasdavid this functionality wasn't present in the previous versions either.

**Comment by diasdavid** [comment]
Ok, no blocker then :)

**Comment by hacdias** [comment]
Any progresses on this @dryajov? If you didn't start, I can try to look at the code and see what I can do.

**Comment by dryajov** [comment]
Go for it - I haven't been able to get to it yet.

**Comment by diasdavid** [comment]
@hacdias 👍 for me as well. Definitely make sure to create a good error for in-proc nodes given that there is no way for two clients to connect to it.

**Comment by dryajov** [comment]
@hacdias have you already started on this, if not I can give it a go now.

**Comment by hacdias** [comment]
@dryajov no, I haven't. Sorry for the late response.

**Comment by dryajov** [comment]
I just did - https://github.com/ipfs/js-ipfsd-ctl/pull/221

**Comment by diasdavid** [comment]
👏🏽👏🏽
