### ISSUE TITLE
Make testing fast again - Bring init options back

### ISSUE THREAD

**Issue by richardschneider** [ipfs/js-ipfsd-ctl#188]
Spawning a deamon on my machine (windows) is extremely slow.  It appears that each go/js command that is run takes ~10 seconds!

More details to follow.

**Comment by dryajov** [comment]
10s is definitely a little slow, but keep in mind that each spawned daemon (unless pointing to an existing repo) will have to init the repo and apply any custom configs before launching the damon, which could get pretty slow. But please do provide details, I'd like to speed this up as much as possible 👍

**Comment by richardschneider** [comment]
Its not just `ipfs init`.  Been sided tracked with other issues, but should have details in an hour or so.

FWI: Timing was done by hand (one onesecond, two one-second, ...) and each command (init, config) took exactly 10s.

Also, are the config settings applied to in-proc IPFS?

**Comment by diasdavid** [comment]
@dryajov when the new version of ipfsd-ctl, we lost the ability to set key size on init. This is really unfortunate as tests are taking forever nowadays.

My proposed solution: 
<img width="805" alt="image" src="https://user-images.githubusercontent.com/1211152/36253404-bd767888-1247-11e8-8bc3-1dc0af0349cb.png">

init should be a bool or object and the object should accept any of the init options:

<img width="510" alt="image" src="https://user-images.githubusercontent.com/1211152/36253430-d76c1db0-1247-11e8-8bf2-4351a69812d0.png">

**Comment by richardschneider** [comment]
@diasdavid what about the PR [smaller keysize when testing](https://github.com/ipfs/js-ipfsd-ctl/pull/198)?

**Comment by diasdavid** [comment]
@richardschneider we are not going to patch globals. This should be an option and not a surprise.

**Comment by dryajov** [comment]
> @dryajov when the new version of ipfsd-ctl, we lost the ability to set key size on init. This is really unfortunate as tests are taking forever nowadays.

We didn't, you can still set it as part of calling `ipfsd.init({keysize: <size>})`. The `init` flag was always a `bool` - 
https://github.com/ipfs/js-ipfsd-ctl/blob/v0.26.0/src/index.js#L9..L15.

That said, I agree it's a valuable option to have. In order to not break the existent implementation, lets leave the `init` as a bool, but add a new property, `initOpts` that would take a `keysize`, that would also support any future init option that we might require.

**Comment by diasdavid** [comment]
I'm curious why the update of js-ipfs, js-ipfs-api and ipfs/interop didn't contemplate that ipfsd.init with reduced key sizes. Was there any blocker?

**Comment by dryajov** [comment]
I don't believe we ever ran our tests with reduced key sizes by default? That said I think we can have our cake and eat it too. Here is what I propose: 

- add the ability to pass the keysize to `spawn` (could be by modifying the existing `init` to take an object or adding an `initOpts` property, whatever works best)
- add the ability to pass the keysize with env variables in addition to passing to `spawn`, we need one for each - js, go and proc
- modify package.json to run test with the desired keysize

Does this sound as an acceptable solution?

**Comment by dryajov** [comment]
> we need one for each - js, go and proc

I'm actually not sure if we need this. In @richardschneider PR #198, there is a check that uses `1024` for go and `512` for js, I'm confused as to why this is, but if we don't need to use different sizes, then we don't need separate variables.

**Comment by richardschneider** [comment]
@dryajov `go-ipfs` enforces min key size of 1024, whereas `js-ipfs` is happy with 512.

@diasdavid 
>  we are not going to patch globals.

It is not patching a global.  It is just using `global` to detect if mocha is being used.

> This should be an option and not a surprise.

Just document that the default key size is 2048 unless running in a `mocha` test.  In which case it's 512 for `js` and 1024 for `go`.

**Comment by dryajov** [comment]
@diasdavid @richardschneider added #203 implementing what I outlined in https://github.com/ipfs/js-ipfsd-ctl/issues/188#issuecomment-366063832

**Comment by diasdavid** [comment]
> I don't believe we ever ran our tests with reduced key sizes by default? 

It was there until the new ipfsd-ctl appeared. A quick git history search:

- https://github.com/ipfs/js-ipfs/blob/b3615b769beb38f81cd64c6f61b2542f3c952c64/test/utils/ipfs-factory-daemon/index.js#L35-L63
- https://github.com/ipfs/js-ipfs/blob/b3615b769beb38f81cd64c6f61b2542f3c952c64/test/utils/ipfs-factory-instance/index.js#L41

> add the ability to pass the keysize to spawn (could be by modifying the existing init to take an object or adding an initOpts property, whatever works best) (thanks @diasdavid )

Let's do this one only and not reinvent the wheel. `ipfs init` has args, let's use them:

<img width="489" alt="image" src="https://user-images.githubusercontent.com/1211152/36320101-f5e13abe-133c-11e8-9d52-009e4724443d.png">

The propname should be `bits`.

Let's follow the proposal on here: https://github.com/ipfs/js-ipfsd-ctl/issues/188#issuecomment-365893965 Let me know if you have questions.

**Comment by dryajov** [comment]
👍 on reusing ini options

**Comment by diasdavid** [comment]
let's finish this one on https://github.com/ipfs/js-ipfsd-ctl/pull/203
