### ISSUE TITLE
Weird behavior with disposable daemons

### ISSUE THREAD

**Issue by mcrider** [ipfs/js-ipfsd-ctl#189]
If I don't pass any options to spawn, it seems like it defaults `disposable` to true -- inspecting ipfsd in the callback shows:

```
[Node]  Node {
[Node]   opts:
[Node]    { type: 'go',
[Node]      disposable: true,
[Node]      start: true,
[Node]      init: true,
[Node]      config:
[Node]       { 'API.HTTPHeaders.Access-Control-Allow-Origin': [Array],
[Node]         'API.HTTPHeaders.Access-Control-Allow-Methods': [Array],
[Node]         'Addresses.Swarm': [Array],
[Node]         'Addresses.API': '/ip4/127.0.0.1/tcp/0',
[Node]         'Addresses.Gateway': '/ip4/127.0.0.1/tcp/0' },
[Node]      exec: undefined },
[Node]   path: '/var/folders/yw/6y_wjm41465dv6bkc86m50g00000gp/T/ipfs_2acdcf543fe5dd65dbdefb45eba8ea68',
[Node]   disposable: true,
...
```

If I explicitly set disposable to false, as in:
```
DaemonFactory
  .create({ type: "go" })
  .spawn({ disposable: false }, (err, ipfsd) => {
    if (err) { throw err; }

    console.log(ipfsd);

    app.listen(app.get("port"), () => {
      console.log("--------------------------------------------------------------");
      console.log(("|  App is running at http://localhost:%d in %s mode"), app.get("port"), app.get("env"));
      console.log("|  Press CTRL-C to stop");
      console.log("--------------------------------------------------------------\n");
    });
  });
```

... `ipfsd` will have `disposable` set to true but `ipfsd.api` will be null. Should it be? Anything weird I'm doing here? I want the daemon to run in a non-disposable way (i.e. I should be able to access documents created after the daemon shuts down). And I need that ipfs-api instance :)

**Comment by dryajov** [comment]
Not really, the `disposable` will only signal `ipfsd-ctl` to create ephemeral nodes, other than that it should respect all the other flags, which in the case are `init=true` and `start=true`. I'm going to try to reproduce this issue.

**Comment by dryajov** [comment]
@mcrider I misread your comment - in `disposable=false`,  you have to both init and start your node manually, the reason is because non disposable nodes will default to well known repo locations (~/.ipfs or ~/.jsipfs) which might be already initialized.  Here is a quick example to init and start your node. Also note, that it's up to you to clean up the repo after the daemon exists. 

```
DaemonFactory
  .create({ type: 'go' })
  .spawn({ disposable: false }, (err, ipfsd) => {
    if (err) {
      throw err
    }

    ipfsd.init((_) => {
      ipfsd.start((_) => {
        ipfsd.api.id((_, id) => {
          if (err) {
            throw err
          }
          console.log('alice')
          console.log(id)
          ipfsd.stop()
        })
      })
    })
  })
```

**Comment by mcrider** [comment]
Thanks for that @dryajov . But when I run your example in a bare-bones reproduction I get `TypeError: Cannot read property 'id' of null`. I integrated it into my app and it seems to sometimes work, is there some sort of race condition perhaps (i.e. ipfsd is not available right away in the start callback)?

**Comment by thisconnect** [comment]
Is there a doc error?
https://github.com/ipfs/js-ipfsd-ctl/#spawn-a-new-daemon-with-dfspawn

disposable bool (default false) 

should be (default true) correct?

**Comment by dryajov** [comment]
@thisconnect thanks for pointing that out! Indeed its a doc error, I'll fix it.

**Comment by dryajov** [comment]
@mcrider that is weird, what OS are you on? It should work, in fact we have several tests set up like that, which should otherwise be failing.

**Comment by mcrider** [comment]
@dryajov I think I was just running into issues with not properly stopping the daemon on exit.  Cleaned everything up and it seems to be working well now.  Thanks for the help!

**Comment by thisconnect** [comment]
thanks @dryajov
