### ISSUE TITLE
`require('ipfsd-ctl')` causes programs to hang

### ISSUE THREAD

**Issue by mappum** [ipfs/js-ipfsd-ctl#19]
Simply requiring this module prevents programs from exiting. You can test this out by making a script that  only contains `require('ipfsd-ctl')` and running it.

**Comment by bcomnes** [comment]
I noticed this last night.  Does it spawn immediately on import?  That might be holding the event loop open.

[![](http://38.media.tumblr.com/89d668b1f2d6ebd640fa0be2ce3f6631/tumblr_nel93wsDQa1s373hwo1_r1_500.gif)](http://nodejsreactions.tumblr.com/post/125353068495/when-you-cant-figure-out-whats-keeping-the-event)

**Comment by VictorBjelkholm** [comment]
Oh, this is quite a horrible one. Anyone have an idea of why, so there is starting point for people wanting to help out?

**Comment by bcomnes** [comment]
@VictorBjelkholm I would double check when the child process spawns.  I belive that will hold the event loop open until the child process returns or is killed.  See https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options for more info on child process's spawn feature.

**Comment by jbenet** [comment]
@bcomnes best use of that gif i've ever seen.

Is this in using `subcomandante`? there may be something wrong there-- it shoudn't hold the event loop.

**Comment by diasdavid** [comment]
Is this still a issue? I've used for other projects and it has been working fine, can you check @mappum @bcomnes ?

**Comment by mappum** [comment]
@diasdavid Yes, it's still an issue in 0.5.4.

**Comment by Dignifiedquire** [comment]
The reason for this is the usage of https://github.com/rynti/node-shutdown-handler/blob/master/shutdown-handler.js. Looking at the code this does not look like to be a good idea to use :(
