### ISSUE TITLE
Debug logging

### ISSUE THREAD

**Issue by richardschneider** [ipfs/js-ipfsd-ctl#193]
If debug logging is enabled,  via DEBUG environment variable, then all the `js-ipfs` tests fails.  It appears that `ipfsd-ctl` does not like debug output.

```
> set DEBUG=*
> aegir test -t node -f test\http-api\interface\block
```

See the [debug.txt](https://github.com/ipfs/js-ipfsd-ctl/files/1671711/debug.txt)

**Comment by dryajov** [comment]
@richardschneider see - https://github.com/ipfs/js-ipfsd-ctl/pull/195#issuecomment-361124921

In esense, if we enable `DEBUG=*` or `DEBUG=ipfs`, etc - it will enable the daemon debug output, which will break our `stdout/stderr` logging. We can use debugging, but we have to be careful to scope it correctly.

**Comment by richardschneider** [comment]
With so many processes running in a test, I really need debug logging to figure out why the tests are failing. 

ipfsd `stdout/stderr` parsing **SHOULD** work with debug logging.

**Comment by dryajov** [comment]
I'd love to get that working, I just don't see how. Once you enable debugging, it will clog `stderr` and will have to workaround parsing leggit errors from conflicting log messages.

**Comment by dryajov** [comment]
This should be done with https://github.com/ipfs/js-ipfsd-ctl/pull/195
