### ISSUE TITLE
Browser tests failing locally

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfsd-ctl#199]
@dryajov do you see this locally? 

<img width="778" alt="image" src="https://user-images.githubusercontent.com/1211152/35844863-92562884-0b07-11e8-8454-43e17be36661.png">

This is blocking me from releasing it for @richardschneider

**Comment by dryajov** [comment]
@diasdavid I just ran them myself on a clean master branch, they worked fine - I'm on MacOS btw. Is there a more complete stack trace that I can look at?

**Comment by diasdavid** [comment]
nvm. I discovered later this was aegir failing for me for not having chrome (tmp machine). Thanks for checking!
