### ISSUE TITLE
Node inspector doesn't work: address already in use

### ISSUE THREAD

**Issue by shumkov** [ipfs/js-ipfsd-ctl#202]
Hello guys, thank you for your amazing work. 

I use `ipfsd-ctl` for spawning IPFS instance in mocha test in a very similar way as in OrbitDb tests.
It's cool but it doesn't work with node inspector:
```
node_modules/.bin/mocha --inspect test/**/*.js

Debugger listening on ws://127.0.0.1:9229/7c0ad2d6-146b-4ae1-bf2c-7e9873c18304
For help see https://nodejs.org/en/docs/inspector


  Storage
    1) "before all" hook: before


  0 passing (33ms)
  1 failing

  1) Storage
       "before all" hook: before:
     Error: non-zero exit code 12

            while running: /Users/ivanshumkov/Projects/dashevo/dashdrive/node_modules/go-ipfs-dep/go-ipfs/ipfs init -b 2048


            Starting inspector on 127.0.0.1:9229 failed: address already in use

      at Stream.listeners.done.once (node_modules/ipfsd-ctl/src/exec.js:39:11)
      at Stream.f (node_modules/once/once.js:25:25)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

```

**Comment by dryajov** [comment]
Unfortunately, thats a known (and annoying ) issue. debugging doesn't work with forked processes in nodejs - https://github.com/nodejs/node/issues/9435

**Comment by shumkov** [comment]
Ahh... Do you know any workarounds? Like this one https://github.com/askmike/gekko/pull/1666?

**Comment by dryajov** [comment]
@shumkov Interesting, thanks for pointing that one out - it's worth a try for sure. Would you feel comfortable sending a PR that fixes this?

**Comment by vmx** [comment]
I just ran into this issue and didn't know there was already one open. I'll do a PR soon.

**Comment by shumkov** [comment]
@dryajov @vmx Seems I'm late :) Don't hesitate to ask my help if needed.
