### ISSUE TITLE
Browser tests failing on MacOS

### ISSUE THREAD

**Issue by richardschneider** [ipfs/js-ipfsd-ctl#206]
What is port 9999? 

See build https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfsd-ctl/detail/graceful-stop/1/pipeline/14

```
Test Browser
listen EADDRINUSE 127.0.0.1:9999
Error: listen EADDRINUSE 127.0.0.1:9999
    at Object._errnoException (util.js:1031:13)
    at _exceptionWithHostPort (util.js:1052:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1523:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:102:10)
error Command failed with exit code 1.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by richardschneider** [comment]
@dryajov Any ideas?  Haven't we seen this before?

**Comment by dryajov** [comment]
I've pinged @VictorBjelkholm about it on IRC - I believe he was to look into it. We can also change the default port for the http server to something more random, but I believe this indicates an issue somewhere else as well - https://github.com/ipfs/js-ipfs/pull/1103#issuecomment-366670887

**Comment by diasdavid** [comment]
<img width="721" alt="image" src="https://user-images.githubusercontent.com/1211152/36532706-5f78d90c-17b9-11e8-9deb-b21b06c2d88c.png">

@dryajov this is a ipfsd-ctl issue, also happening on Jenkins here - https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfsd-ctl/detail/PR-203/19/

**Making it be a port random would only hide the issue, the real problem is that the http server is not closed properly**.

**Comment by VictorBjelkholm** [comment]
@diasdavid I'm working on this right now.

Are you sure about the real problem? I'll make sure it's closed then, but it could also be that the port is used on macOS for other purposes. Real fix would be to make sure port is ephemeral + making sure server is closed IMHO.

**Comment by diasdavid** [comment]
Update: Let's see https://github.com/ipfs/js-ipfsd-ctl/pull/209 :)

**Comment by VictorBjelkholm** [comment]
Fair enough. My theory is that tests were killed in a stage where the http-server was not properly killed, but this doesn't happen always, just sometimes (cancelled builds?).

**Comment by diasdavid** [comment]
Verdict: https://github.com/ipfs/js-ipfsd-ctl/pull/209#issuecomment-367638325

**Comment by diasdavid** [comment]
This was fixed.
