### ISSUE TITLE
Map config object to CLI args?

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-ipfsd-ctl#207]
The in-process node [maps CLI `args` to `config`](https://github.com/ipfs/js-ipfsd-ctl/blob/cf794cdb047c0ee1aaa8aff923c1fd0bd15e9051/src/ipfsd-in-proc.js#L47-L57) but the daemon node does not map `config` to `args`.

I was trying to create a daemon node and passing `config` to enable pubsub, but the node was not configured to enable pubsub.

Should it also map `config` object to CLI `args`? Do we need both `config` and `args`?

**Comment by diasdavid** [comment]
For consistency, we need config and args because there is different sets of info that go in each. That said, things like "EXPERIMENTAL" flags on js-ipfs are not config, they are options (aka args for the in proc node). This is a bug.

**Comment by negamaxi** [comment]
@diasdavid currently there is no way to enable pubsub for js-ipfs daemon?

**Comment by vaibhav6233m** [comment]
@diasdavid Need some help on this. #282 @negamaxi Did you by any chance find any way to enable pubsub, relay and dht in js-ipfs.

**Comment by negamaxi** [comment]
@vaibhav6233m not yet.
