### ISSUE TITLE
In proc node config not applied

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-ipfsd-ctl#208]
I'm trying to enable `EXPERIMENTAL.dht` for my in-proc node:

```js
df.spawn({ config: { EXPERIMENTAL: { dht: true } } }, /* ... */)
```

The DHT experiment is not enabled because the in process node does not use the `config` property to configure the node, it expects `EXPERIMENTAL` to be in the root of the options object:

https://github.com/ipfs/js-ipfsd-ctl/blob/cf794cdb047c0ee1aaa8aff923c1fd0bd15e9051/src/ipfsd-in-proc.js#L36

**Comment by dryajov** [comment]
Hmm, I believe that we can deprecate the use of options in `ipfsd-ctl` for `proc` types and always use the `config` key. That will make it consistent across all daemon types, which currently don't use options at all.

**Comment by alanshaw** [comment]
Any progress on this? I've encountered it again...

**Comment by jacobheun** [comment]
I created https://github.com/ipfs/js-ipfsd-ctl/pull/268 to resolve a separate issue I was having with `options.Bootstrap` not being overridable (which is painful when testing private networks). It does not do what @dryajov is proposing for the experimental args, but it does pass the config to the created IPFS node.

**Comment by vasco-santos** [comment]
I would go with @jacobheun solution by now, and we can have @dryajov solution afterward. What do you think? @dryajov @alanshaw

**Comment by daviddias** [comment]
@hugomrdias does this issue still apply?

**Comment by hugomrdias** [comment]
not sure but i can guarantee in the next version this will not be a problem, already made tests for it
