### ISSUE TITLE
Cant' find go-ipfs-dep module

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/js-ipfsd-ctl#213]
index.js (copy-paste from readme.md):
```
const IPFSFactory = require('ipfsd-ctl')
const f = IPFSFactory.create()

f.spawn(function (err, ipfsd) {
  if (err) { throw err }
  ipfsd.api.id(function (err, id) {
    if (err) { throw err }
    console.log(id)
    ipfsd.stop()
  })
})
```
Running:
```
$ node index.js
/home/user/projects/victorbjelkholm/asciinema-ipfs/node_modules/ipfsd-ctl/src/utils/find-ipfs-executable.js:34
  throw new Error('Cannot find the IPFS executable')
  ^

Error: Cannot find the IPFS executable
    at module.exports (/home/user/projects/victorbjelkholm/asciinema-ipfs/node_modules/ipfsd-ctl/src/utils/find-ipfs-executable.js:34:9)
    at new Daemon (/home/user/projects/victorbjelkholm/asciinema-ipfs/node_modules/ipfsd-ctl/src/ipfsd-daemon.js:53:60)
    at FactoryDaemon.spawn (/home/user/projects/victorbjelkholm/asciinema-ipfs/node_modules/ipfsd-ctl/src/factory-daemon.js:130:18)
    at Object.<anonymous> (/home/user/projects/victorbjelkholm/asciinema-ipfs/index.js:4:3)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
```
Install with yarn:
![image](https://user-images.githubusercontent.com/459764/37034295-22ba6ae6-2149-11e8-9a39-a60dd47b10eb.png)

Install with npm:
![image](https://user-images.githubusercontent.com/459764/37034460-a4c56554-2149-11e8-8201-ea5557cf4dc7.png)

```
{ npm: '5.6.0',
  ares: '1.13.0',
  cldr: '32.0',
  http_parser: '2.7.0',
  icu: '60.1',
  modules: '59',
  napi: '2',
  nghttp2: '1.29.0',
  node: '9.5.0',
  openssl: '1.0.2n',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.19.1',
  v8: '6.2.414.46-node.18',
  zlib: '1.2.11' }
```

Here is a commit that moves `go-ipfs-dep` from `dependencies` to `devDependencies`, which might have something to do with it: https://github.com/ipfs/js-ipfsd-ctl/commit/1cfbd08bc9641548071fd70afc3e31365a391c81#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by diasdavid** [comment]
@VictorBjelkholm I see you went the whole length on this one but skipped to read the README.

https://github.com/ipfs/js-ipfsd-ctl#batteries-not-included-bring-your-own-ipfs-executable

<img width="973" alt="image" src="https://user-images.githubusercontent.com/1211152/37036474-15be2cf4-2150-11e8-9841-767650e30ac6.png">

**Comment by VictorBjelkholm** [comment]
Ugh, yes indeed, I did no bother as I thought it was batteries included, like before. Sorry, my mistake.

Although, with that said, if don't include the batteries, we should have a better error message, guiding users to the readme in case neither js-ipfs or go-ipfs could be found.

**Comment by diasdavid** [comment]
@VictorBjelkholm go for it. Always 👍  for improving UX :)

**Comment by diasdavid** [comment]
@VictorBjelkholm are you on top of it?

**Comment by VictorBjelkholm** [comment]
This was fixed in https://github.com/ipfs/aegir/pull/198

**Comment by musicsmithnz** [comment]
I got the same error, even though I installed "ipfs". I then tried again with "go-ipfs-dep" and it worked fine. I'm not sure why, but the plain "ipfs" package doesn't seem to work in this setup.
