### ISSUE TITLE
In proc nodes can not be spawned on top of existing repos

### ISSUE THREAD

**Issue by JonKrone** [ipfs/js-ipfsd-ctl#214]
In-process js-ipfs instances are not aware of whether or not they have spawned on top of an existing repo. This basically breaks the node as it can neither `.start` or `.init`.

I believe this is the cause of an error mentioned in a TODO here:
https://github.com/ipfs/js-ipfsd-ctl/blob/151303ce495b456188d2201421706358afcd5b5d/test/spawn-options.spec.js#L121

I think a fix for this can largely mirror how a js-ipfs instance works if the repo exists.

Another in-proc node issue that might be good to group with this: https://github.com/ipfs/js-ipfsd-ctl/issues/208

**Comment by linonetwo** [comment]
+1 .  I was wondering how ipfs-desktop achieve this . https://github.com/ipfs-shipyard/ipfs-desktop/blob/master/src/index.js#L238.

I copy the code but I errors, then I found out, I'm using ```DaemonFactory.create({ type: 'proc', exec: require('ipfs'), port })``` but ipfs-desktop is just using ```DaemonFactory.create()``` .

**Comment by linonetwo** [comment]
related? https://github.com/ipfs/js-ipfs/issues/1245

**Comment by JonKrone** [comment]
@linonetwo 
> I was wondering how ipfs-desktop achieve this

Yeah, ipfs-desktop is not using a proc node but there is a fix in https://github.com/ipfs/js-ipfsd-ctl/pull/212 ([here](https://github.com/ipfs/js-ipfsd-ctl/pull/212/files#diff-a64c691b43b66870588c26e5ceb75ea7R55)) that should allow ipfs-desktop to skip that check and rely on the `initialized` property of the node they spawn.

> related? ipfs/js-ipfs#1245

I don't think that it is. They both have to do with initialization but I think that they're separate. This particular issue is with js-ipfsd-ctl and that issue isn't spawning any daemons.

**Comment by dryajov** [comment]
@JonKrone is this still an issue?

**Comment by linonetwo** [comment]
@dryajov  Seems fixed, I'm using 0.28.2. @JonKrone  I think this can be closed.

**Comment by linonetwo** [comment]
So now we can copy the huge repo to a flash drive, and init on it at another country.
