### ISSUE TITLE
Spawn go daemon does not work with Node.js v9.9.0+

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-ipfsd-ctl#223]
`.spawn` never calls back.

**Comment by VictorBjelkholm** [comment]
We're already testing js-ipfsd-ctl on nodejs 9.2.0. Is there a specific version you're thinking about?

**Comment by alanshaw** [comment]
Possibly, I'm on 9.10.0. I'll add a reproducible example when I get a sec.

**Comment by VictorBjelkholm** [comment]
I see. I added a test-run with 9.10.0 activated (together with the old ones we're already running): https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfsd-ctl/detail/master/40/pipeline/

**Comment by VictorBjelkholm** [comment]
Nevermind, test with just 9.10.0: https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfsd-ctl/detail/master/41/pipeline

**Comment by VictorBjelkholm** [comment]
On Jenkins (linux at least), the node-gyp builds are not even working properly: https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfsd-ctl/detail/master/41/pipeline/13

**Comment by dryajov** [comment]
Taking a look now as well.

**Comment by dryajov** [comment]
BTW - everything up until 9.8.0 seems to work as expected (I'm on 9.0.0 myself), v9.10.0 is pretty broken.

**Comment by VictorBjelkholm** [comment]
This is probably related to https://github.com/jbenet/node-subcomandante/pull/6

**Comment by travisperson** [comment]
We just published v1.2.0 for node-subcomandante, which should fix this issue. I ran the tests locally, but am running into what I believe is a type check issue when running `js-ipfs` in proc.

https://github.com/ipfs/js-ipfs/issues/1331

**Comment by travisperson** [comment]
```
Package ipfsd-ctl@0.32.1 wants ipfs-repo@^0.19.0
 from .
 resolves to ./node_modules/ipfs-repo@0.19.0

Package ipfs-repo@0.19.0 wants ipfs-block@~0.7.1
 from ./node_modules/ipfs-repo
 resolves to ./node_modules/ipfs-repo/node_modules/ipfs-block@0.7.1
```
---------
```
Package ipfs@0.28.2 wants ipfs-repo@~0.18.7
 from ./node_modules/ipfs
 resolves to ./node_modules/ipfs/node_modules/ipfs-repo@0.18.7

Package ipfs-repo@0.18.7 wants ipfs-block@~0.6.1
 from ./node_modules/ipfs/node_modules/ipfs-repo
 resolves to ./node_modules/ipfs-block@0.6.1

Package ipfs@0.28.2 wants ipfs-block@~0.6.1
 from ./node_modules/ipfs
 resolves to ./node_modules/ipfs-block@0.6.1
```

This resolves down into:

 - `ipfsd-ctl` wants `ipfs-repo@0.19.0`, and `ipfs` wants `ipfs-repo@0.18.7`,
 - `ipfs-repo@0.19.0` uses `ipfs-block@0.7.1`
 - `ipfs-repo@0.18.7` uses `ipfs-block@0.6.1`

Both of these packages check blocks differently, so they are not compatible.

Downgrading the `ipfs-repo` dependency of `ipfsd-ctl` to `ipfs-repo@0.18.7` fixes the issue and all tests now pass on Node.js v9.9.0!

**Comment by travisperson** [comment]
> Weird this would show only under v9.9.0?

Sorry if this was confusing. The block error has nothing to do with Node.js v9.9.0 or `node-subcomandante`, I'm just unable to verify that the newly published version of `node-subcomandante` works in master due to the block issue _without_ downgrading the dependency `ipfs-repo`.

Everything works correctly in Node.js v9.9.0 if I downgrade `ipfs-repo` to a compatible version that works with the `js-ipfs` dependency (v0.28.2).

**Comment by dryajov** [comment]
@travisperson oh! Got you, thanks for clarifying - this makes sense then 👍
