### ISSUE TITLE
Stop daemon on process exit

### ISSUE THREAD

**Issue by artvinn** [ipfs/js-ipfsd-ctl#224]
Hi guys. I am running a non-disposable node and trying to stop the daemon on process exit(SIGINT). The issue is that `api` and `repo.lock` files in repo are not cleaned up.

```javascript
process.on('SIGINT', () => {
  console.log ('CTRL+C...');
  ipfsApi.stop(err => console.log(err))
});
```
And it throws following error:

```javascript
{ Error: connect ECONNREFUSED 127.0.0.1:58369
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1170:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 58369 }
```

go-ipfs-dep: 0.4.14
ipfsd-ctl: 0.31.0
Windows 10

Would appreciate any help, thank you :)

**Comment by dryajov** [comment]
Could you try it with a js-ipfs node (`type: 'js'`)? Graceful shutdown has been implemented in ipfsd-ctl since the last couple of versions, I wonder if there is a regression in go-ipfs?

**Comment by artvinn** [comment]
Tried with `type: 'js'` and the behavior is the same.

**Comment by dryajov** [comment]
@artvinn do you wait for `ipfsApi.stop()` to come back before exiting your process? For background please check #226. The gist of the issues is that you have to give time to `ipfsd-ctl` to exit before exiting your process.

**Comment by artvinn** [comment]
@dryajov you can close this now, as #226 answered it. Thanks.
