### ISSUE TITLE
Trying to start non-disposable node fails on second attempt

### ISSUE THREAD

**Issue by negamaxi** [ipfs/js-ipfsd-ctl#226]
Electron app. Trying to start ipfs daemon in a renderer process with this piece of code:
```javascript
    const factory = IPFSFactory.create({ type: "go" })
    const startDaemon = (ipfsd) => {
      ipfsd.start(daemonFlags, (err, api) => {
        if (err) {
          reject(err)
        }
        resolve(api)
      })
    }
    factory.spawn({ disposable: false, repoPath: '/my/repo/path/' }, (err, ipfsd) => {
      if (err) {
        reject(err)
      }
      if (ipfsd.initialized) {
        startDaemon(ipfsd)
      } else {
        ipfsd.init((err) => {
          if (err) {
            resolve(err)
          }
          startDaemon(ipfsd)
        })
      }
    })
```
If repo doesn't exists it works as expected: new repo get initialized, daemon starts, I can see it in my processes list and in `subprocess` field of `ipfsd`. But the next time demon does not start, despite the fact that `initialized` and `_started` fields are all true. No errors, `subprocess` field is null. Am I missing something?

**Comment by dryajov** [comment]
Thanks for reporting this - it should indeed work for your use case. This seems like a bug.

**Comment by travisperson** [comment]
Most likely the reason for this is because under `$IPFS_PATH` there exists an `api` file. In this case, ipfsd-ctl will skip setting up the daemon and simply return an `ipfs-api` instance for the address within the file.

We are only allowing 10500ms before we issue a `SIGKILL`. This will not allow the daemon to properly clean up and will leave around the `api` and `repo.lock` files under `$IPFS_PATH`.

This would be my guess to why you are having this issue. We probably should clean up these files ourselves if we ever forcefully kill the daemon.

**Comment by dryajov** [comment]
Thanks @travisperson! That could indeed be the reason. 

@negamaxi could you check if the `api` file is being left behind after ipfsd-ctl shutdowns? 

We did experiment with the `10500` (increased from `~7000` ms AFAIR), way back when we we're adding js-ipfs support and found it to be sufficient, but it could fail on certain envs I'm guessing.

@hacdias Have you experienced anything like this in `ipfs-desktop`?

**Comment by dryajov** [comment]
@negamaxi I was able to reproduce this behavior by terminating the `ipfsd-ctl` process abruptly, which doesn't give `ipfs` a chance to shutdown gracefully. This could happen under a number of scenarios, but a few obvious ones I can think off are:

- kill -9 the ipfsd-ctl or ipfs process
- if running under an ide and/or debugger, stopping the process will usually kill it abruptly
- slower system might take longer than the specified (`10500ms`) graceful timeout given to `ipfs` to shutdown before ipfsd-ctl kills it

**Comment by negamaxi** [comment]
@dryajov both `repo.lock` and `api` files confirmed. Removing `api` file solves the issue. I'm not sure how exactly ipfs terminates right now, it's just happens when I close electron window. Suppose I should intercept close event and use `ipfsd.stop()` method to be sure ipfs shuts down gracefully?

**Comment by negamaxi** [comment]
@dryajov also should I check for those two files and remove them on app start? There are definitely will be cases when app won't be able to shut down gracefully.

**Comment by travisperson** [comment]
If you are not shutting down the daemon it self through `ipfsd.stop()` there is a high chance of the daemon not shutting down gracefully.

Take a look at [ipfs-shipyard/ipfs-desktop](https://github.com/ipfs-shipyard/ipfs-desktop/blob/657373a195a805424acf2bf746fcddf08d05fbfd/src/index.js#L269-L273) and how it handles the daemon management. It seems to do a fairly good job.

You may not want to remove those files on startup, as there could be a daemon running. However, if you are still having issues after implementing `ipfsd.stop()` it might be an okay workaround till `ipfsd-ctl` itself does this cleanup when it forcefully shutdowns daemons.

**Comment by negamaxi** [comment]
@dryajov @travisperson big thanks to both of you.

**Comment by olizilla** [comment]
Of note, Desktop was manually clearing out the `api` file it  found one  was preventing start-up, but that isn't safe as some folks manually craft an `api` file to point to a deamon running as a restricted user: https://github.com/ipfs-shipyard/ipfs-desktop/pull/722#issuecomment-444139824

Now we've removed the logic to clean up the repo, we keep hitting this problem. `ipfs deamon` can be killed and restarted from the commandline, and sometimes it will leave an api file. `ipfsd-ctl` doesn't handle the situation, but  it would be super helpful if it could.
