### ISSUE TITLE
Misleading documentation of f.spawn

### ISSUE THREAD

**Issue by artvinn** [ipfs/js-ipfsd-ctl#231]
Hi guys. Found an information in docs a little misleading.

[Docs](https://github.com/ipfs/js-ipfsd-ctl#spawn-a-daemon-with-fspawnoptions-callback) state that you can pass ```args``` array with options, however if daemon is non-disposable these args are not taken into account later when calling ```start()``` and you still need to pass ```flags``` argument directly. 
https://github.com/ipfs/js-ipfsd-ctl/blob/b781fbb77cc461fe09cb625f8cca037ff5942464/src/ipfsd-daemon.js#L212-L221

Not a big deal but took me some time to figure it out. I thought maybe we could account for opts object in start method, like:

```js
if (typeof flags === 'function') {
      callback = flags
      flags = this.opts.args || []
    }
```
Or just mention about it in the docs somewhere?

Thanks.

**Comment by dryajov** [comment]
Hmm... good catch! Thanks!

I agree we need to merge this args with the ones passed to `.spawn`, with the condition that flags passed here, override the ones given to `.spawn`.
