### ISSUE TITLE
Program run via `exec` and outputting to stderr assumes failure

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/js-ipfsd-ctl#234]
Currently if you try to run a js-ipfs daemon via js-ipfsd-ctl with `DEBUG` set to `*`, ipfsd-ctl will not work correctly and assume that the js-ipfs daemon outputs errors, since the npm module `debug` outputs to stderr.

Rather than just seeing if there is data on stderr and fail if there is, we should save the data and output it if the exit status is not 0.

Line in question that makes the assumption: https://github.com/ipfs/js-ipfsd-ctl/blob/b781fbb77cc461fe09cb625f8cca037ff5942464/src/utils/exec.js#L60

**Comment by dryajov** [comment]
Thanks @VictorBjelkholm! This sounds reasonable and seems like it would fix our logging issues 👍

**Comment by achingbrain** [comment]
This should be fixed by #270
