### ISSUE TITLE
How do i access the gateway?

### ISSUE THREAD

**Issue by lukas2005** [ipfs/js-ipfsd-ctl#236]
I want to load my web front end from IPFS in an electron app.
I currently have this code:
```js
const electron = require("electron");             
const {app, BrowserWindow} = electron;

const IPFSFactory = require("ipfsd-ctl");

let mainWindow;

const ipfsd = IPFSFactory.create();

ipfsd.spawn((err, ipfsNode) => {
	ipfsNode.setConfig("Addresses.Gateway", "/ipv4/127.0.0.1/tcp/1324", (err) => {	
		ipfsNode.start((err, ipfs) => {
			//ipfs.pin.add();
			ipfs.config.get().then((config) => {
				console.log(JSON.stringify(JSON.parse(config), null, "\t"));
			});
		});
	});
});

app.on("ready", () => {
	mainWindow = new BrowserWindow();

	mainWindow.loadURL("http://localhost:1324/ipns/QmVT7hWKntLBDkZQLjR4D2vSXbcnYBRMwua7SknnVzdXo6/");
});
```
but the gateway doesn't work. Do I have to add any options?

**Comment by dryajov** [comment]
It doesn't seem like you're waiting for the node to start. Perhaps, you could try placing your `spawn` code inside the `on('ready')`? Just an idea....

**Comment by lukas2005** [comment]
Hmm looks like it didn't change anything. I can't even access the gateway thru the browser

**Comment by lukas2005** [comment]
Nevermind now it works :P

**Comment by xuruijing** [comment]
@lukas2005  Have you tried the gateway in PROC type? I have been unable to access the gateway in this type
