### ISSUE TITLE
Make CI green again

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/js-ipfsd-ctl#242]
Currently, master has not had a passing build since 6 of April (https://ci.ipfs.team/job/IPFS/job/js-ipfsd-ctl/job/master/) and none of the PRs are having green builds right now.

Since js-ipfsd-ctl is a integral part in our development and testing, we have to make the tests pass as long as the code is correct. Having flaky tests is a deal breaker, as we start ignoring the test results.

I'm not sure why the builds are not passing, but we should stop adding new features or fixes until we can trust CI, as otherwise we cannot safely merge changes.

**Comment by dryajov** [comment]
Agree. Now that most changes related to `class-is` have been bubbled, it should be green again. Looking into it now.

**Comment by VictorBjelkholm** [comment]
@dryajov seems we could already open a PR and [manually override the node modules](https://github.com/ipfs/jenkins-libs/#example-2) to at least see if makes it green, correct?

**Comment by dryajov** [comment]
@VictorBjelkholm We can, but that would still break for our users, wont it? 

I think what we need is to release a hot fix `js-ipfs` with the locked `js-ipfs-repo` version to `0.20.0`. The reason this is all broken now, is because we used `^` for `0.x.x` versions, and broke semantic versioning in `js-ipfs` - this is now broken for **_everybody_** not just `ipfsd-ctl`. I think this is pretty bad, but fixing it just for the CI won't make this issue go away.

**Comment by dryajov** [comment]
Ah, I take that back @VictorBjelkholm - we only need to pin it down here, js-ipfs is fine as it is still on `0.18.x`...

**Comment by dryajov** [comment]
The `^` vs `~` issue still stands, as we're wrongly using `^` for `ipfs-version` here - https://github.com/ipfs/js-ipfsd-ctl/blob/master/package.json#L89, which forces it to pick up the latest, `ipfs-repo` version `0.21.0`. We need to pin it to `~0.20.0`.

**Comment by VictorBjelkholm** [comment]
@dryajov yeah, I just wanted to confirm that what we think would solve the issue, actually solves it (reproduce it externally so we can be 100% nothing more needs to get done).

Speaking about `^` vs `~`, is there a reason we don't just specify the versions as-is, without any version ranges? Having dependencies automatically switch out from under you feels like a bad default. Way easier to just remember "no version ranges" than "Use ~ for everything below 1.0.0 and ^ for everything above 1.0.0" as well. We could also enforce this via CI if we'd wish (even the ~/^ rule could be enforced)

**Comment by VictorBjelkholm** [comment]
@dryajov lock files would be nice. Would be even nicer with lock files that works both for yarn (I know many of the devs that uses yarn (and me) + CI uses yarn) and npm (probably most people still using npm?), since they have different ones. Locking the version directly in package.json works for both though.

**Comment by dryajov** [comment]
good point, forgot about incompatible lock files 😭

**Comment by diasdavid** [comment]
@vasco-santos now that js-ipfs has been released, you can updates and get CI green again.

**Comment by vasco-santos** [comment]
@diasdavid [CircleCI](https://circleci.com/gh/ipfs/js-ipfsd-ctl/836?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) is not green yet!

Last time it was green was in @dryajov [PR](https://github.com/ipfs/js-ipfsd-ctl/pull/243). Dmitriy do you know what is wrong now?

**Comment by dryajov** [comment]
The failures come from the version logic:

<img width="903" alt="screen shot 2018-05-30 at 7 09 12 pm" src="https://user-images.githubusercontent.com/1094341/40756003-40af254a-643e-11e8-9b1b-ed267a30652f.png">
<img width="1299" alt="screen shot 2018-05-30 at 7 08 48 pm" src="https://user-images.githubusercontent.com/1094341/40756004-40c5cd72-643e-11e8-9988-62237c88b7d6.png">


There is a bug in js-ipfs introduced with https://github.com/ipfs/js-ipfs-repo/pull/164/files#diff-1fdf421c05c1140f6d71444ea2b27638R216. Changing the error message broke version handling, which ignores uninitialized repos and sources the version directly from the package if no repo exists. Here is a fix https://github.com/ipfs/js-ipfs/pull/1374.

**Comment by vasco-santos** [comment]
Thanks for your analyzes @dryajov !

**Comment by alanshaw** [comment]
@dryajov I'm confused, https://github.com/ipfs/js-ipfs-repo/pull/164/files#diff-1fdf421c05c1140f6d71444ea2b27638R216 didn't change the error message

**Comment by vasco-santos** [comment]
CI is green again!! 🙌
Thank you all
