### ISSUE TITLE
Also bring your own API?

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-ipfsd-ctl#254]
To quote the README:

> Batteries not included. Bring your own IPFS executable.

How about also bring your own API?

It means that you can use an API that is compatible with the node you're spawning.

**Comment by vasco-santos** [comment]
Hey @alanshaw !

I think it would be a good enhancement to the `js-ipfsd-ctl`, as well!

**Comment by hugomrdias** [comment]
@alanshaw this can be closed with this PR https://github.com/ipfs/js-ipfsd-ctl/pull/261
