### ISSUE TITLE
What's the difference between proc and js types

### ISSUE THREAD

**Issue by xuruijing** [ipfs/js-ipfsd-ctl#264]
`proc ` ,  `js`   What's the difference between these two types?  I use the type `js`, the gateway address `IPFS gateway: /ip4/127.0.0.1/tcp/52403`  after startup, and when I start with the type `proc `, the gateway is `IPFS gateway: /ip4/127.0.0.1/tcp/0`  , like the gateway doesn't work

**Comment by xuruijing** [comment]
@vasco-santos Can I launch the gateway in `proc` mode?

**Comment by vasco-santos** [comment]
Hey @xuruijing 

Basically, when using `type: 'js'` and `type: 'go'` , the daemon node is started behind the scenes (using the installed versions).

If you use tye `type: proc`, you are free to use your own IPFS executable. This way, you have to provide an executable to the `spawn` call.

```js
const IPFS = require('ipfs')
const DaemonFactory = require('ipfsd-ctl')

DaemonFactory
  .create({ type: 'proc' })
  .spawn({ exec: IPFS }, (err, ipfsd) => {
    if (err) {
      throw err
    }

    ipfsd.api.id((err, id) => {
      if (err) {
        throw err
      }

      console.log('js-ipfs')
      console.log(id)
      ipfsd.stop(() => process.exit(0))
    })
  })
```

So yeah, you can launch the gateway in proc mode, as well.

**Comment by xuruijing** [comment]
I wrote it the same way, but I commented out the last line of code（ `ipfsd.stop(() => process.exit(0))` ），Then use the browser to access 127.0.0.1:9090, the display is unsuccessful. I added a line of code to show the gateway address（ `console.log('IPFS gateway: ${ipfsd.gatewayAddr}')` ）, and the result is this( `IPFS gateway: /ip4/127.0.0.1/tcp/0`).

**Comment by xuruijing** [comment]
@vasco-santos According to the above code, I did not access the gateway, is there anything missing?

**Comment by vasco-santos** [comment]
@xuruijing 

Basically, the `proc` daemon runs an IPFS Node inside its current process. This way, the IPFS gateway is launched as you can see, but you cannot interact with it externally since it is inside the process scope.

For interacting by HTTP with the daemon using this module, you have to use the other types. 

It would be helpful if you create a PR explaining this in the `README.md`.
