### ISSUE TITLE
cannot access the gateway in PROC mode

### ISSUE THREAD

**Issue by xuruijing** [ipfs/js-ipfsd-ctl#266]
Start the DAEMON in PROC mode and cannot access the gateway. The configuration `ipfsd.gatewayAddr`  is displayed as`ip4/127.0.0.1/tcp/0`. Am I calling the wrong or the code Bug?

**Comment by vasco-santos** [comment]
Hey @xuruijing 

I explained why you cannot access it in this [issue](https://github.com/ipfs/js-ipfsd-ctl/issues/264#issuecomment-396324490). Did this clear your doubts regarding this issue?

**Comment by xuruijing** [comment]
I understand your explanation. Thank you very much. 
Can I manually start this gateway by code to do its job? Or is there a similar way to do it?

**Comment by vasco-santos** [comment]
You can interact with the node programmatically, not by network communication. So, as far as I know, you cannot do it by code, or at least not easily. I recommend you to use the other types of daemon instead.

**Comment by diasdavid** [comment]
@xuruijing a `proc` node is an instance, not a daemon. Only the daemons expose the gateway. 

See how here https://github.com/ipfs/js-ipfsd-ctl/blob/master/examples/local-disposable/local-disposable.js#L11-L47
