### ISSUE TITLE
ipfs.name.publish and ipfs.name.resolve is error

### ISSUE THREAD

**Issue by xuruijing** [ipfs/js-ipfsd-ctl#273]
I use ipfs.name.publish and ipfs.name.resolve, The results showed`TypeError: Unable to get property 'resolve' of undefined or null reference`. Is jsipfs not implementing both methods？But there is in the ipfs-api

**Comment by vasco-santos** [comment]
Hello @xuruijing 

I am currently implementing IPNS for `js-ipfs` as you can see [here](https://github.com/ipfs/js-ipfs/pull/1400). Consequently, the IPNS is not available through `js-ipfs` yet.
