### ISSUE TITLE
TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by vaibhav6233m** [ipfs/js-ipfsd-ctl#276]
I am trying a simple example to spawn IPFS node inside the electron main process.

I am getting this issue if I try to pass custom options inside f.spawn() method.
If I don't pass any options then it starts the node.

See SS:

![screenshot from 2018-07-04 15-47-09](https://user-images.githubusercontent.com/29979122/42271810-dd1ef526-7fa1-11e8-8a80-d82c7f5a2c9e.png)
![screenshot from 2018-07-04 15-47-29](https://user-images.githubusercontent.com/29979122/42271815-dea52f82-7fa1-11e8-9c5f-190eea47be36.png)

Thanks in advance.

**Comment by vaibhav6233m** [comment]
I came to know that if you pass `disposable: true` then the node starts with the settings provided, but I still need to maintain the custom node repo inside electron app config folder.

**Comment by diasdavid** [comment]
Being fixed at #304.
