### ISSUE TITLE
Spawn options - args

### ISSUE THREAD

**Issue by vasco-santos** [ipfs/js-ipfsd-ctl#277]
I was trying to add the pass cli argument to the [spawned](https://github.com/ipfs/js-ipfsd-ctl/blob/master/README.md#spawn-a-daemon-with-fspawnoptions-callback) daemon and it was problematic because we have to pass the argument and its value in different entries of the args array.

```js
args: ['--pass', 'passwordSuperRandom']
```

We should allow to use them both in the same entry of the array, or provide a better documentation for this args with an example.

**Comment by hugomrdias** [comment]
yeah it can be weird we should improve the docs and link to https://github.com/jbenet/node-subcomandante
