### ISSUE TITLE
IPFS Companion shows no peers

### ISSUE THREAD

**Issue by negamaxi** [ipfs/js-ipfsd-ctl#278]
If IPFS node spawned with a `defaultAddr` option set to `false` (default value) than peers number is always at 0. Is it expected behavior? 

![ipfs-no-peers](https://user-images.githubusercontent.com/16529171/42440112-5c0ffbf4-836d-11e8-88f5-12d2fd52e056.png)

**Comment by negamaxi** [comment]
I've found [this issue](https://github.com/ipfs/go-ipfs/issues/5146) in go-ipfs repo that seems to be related.

**Comment by Stebalien** [comment]
What's the `defaultAddr` option?

**Comment by negamaxi** [comment]
@Stebalien defaultAddr**s**. If set to `true` ipfsd-ctl [will not set](https://github.com/ipfs/js-ipfsd-ctl/blob/master/src/factory-daemon.js#L125) [random ports](https://github.com/ipfs/js-ipfsd-ctl/blob/master/src/defaults/config.json) for API and gateway.

Actually, the issue is gone in the latest go version (4.0.16). Closed I guess.

**Comment by Stebalien** [comment]
So, the issue there wasn't the random port. It was the localhost only port.
