### ISSUE TITLE
speed boost: gen 200 PeerIds in advance

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfsd-ctl#280]
Me, @hugomrdias and @vasco-santos talked about this last week. If we have 200 PeerIds generated before hand, we can add a option to ipfsd-ctl that tells it just being used for tests (e.g. { test: true }) so that it takes from the PeerId pool rather than trying to gen PeerIds each time. This will dramatically speed up tests everywhere.

**Comment by hugomrdias** [comment]
check PR https://github.com/ipfs/js-ipfsd-ctl/pull/284
