### ISSUE TITLE
Listen on 0.0.0.0 by default

### ISSUE THREAD

**Issue by Stebalien** [ipfs/js-ipfsd-ctl#281]
By default, js-ipfsd-ctl spawns daemons that listen on localhost only. Given that it supports spawning non-disposable daemons, it should probably listen on 0.0.0.0 by default. Alternatively, this behavior should be well documented.

**Comment by agentofuser** [comment]
I ran into this problem, and calling `spawn` with `defaultAddrs: true` fixed it.
