### ISSUE TITLE
Option to spawn daemons using the globally installed binary

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfsd-ctl#29]
It would be sweet to be able to use the ipfs bin install in the host, so that we can select any IPFS version, even those who weren't released yet, to be tested with js-ipfs-api tests, as an example :)

**Comment by jbenet** [comment]
indeed. right now i'm copying it in and it's annoying.

**Comment by haadcode** [comment]
Isn't this already possible with IPFS_EXEC=/path/to/other/ipfs/bin <run command>? 

If not, let's definitely get this in. If yes, is IPFS_EXEC not the solution needed here?

**Comment by VictorBjelkholm** [comment]
@haadcode yes, definitly possible today with `IPFS_EXEC`, see here: https://github.com/ipfs/js-ipfsd-ctl/blob/5de559d468d4f4bdd56bd8ea9f5ce12cd6a1a7e3/src/node.js#L63

**Comment by diasdavid** [comment]
- [ ] Needs documentation

**Comment by dignifiedquire** [comment]
> If you need want to use an existing ipfs installation you can set $IPFS_EXEC=/path/to/ipfs to ensure it uses that.

This is in the current readme

**Comment by diasdavid** [comment]
✔️
