### ISSUE TITLE
cannot measure perf gains with pre-gen ids

### ISSUE THREAD

**Issue by hugomrdias** [ipfs/js-ipfsd-ctl#295]
linked js-ipfs master with ctl and double checked the code path was right just to make sure these results were real.
/cc @mkg20001 

```
go 1024 x 0.50 ops/sec ±12.86% (7 runs sampled)
js 512 x 0.24 ops/sec ±0.88% (6 runs sampled)
js disposable x 0.24 ops/sec ±1.03% (6 runs sampled)
Fastest is go 1024
```
```js
const suite = new benchmark.Suite()

suite
  .add('go 1024', {
    defer: true,
    fn: function (defer) {
      const f = create({ type: 'go' })
      f.spawn({
        initOptions: { bits: 1024 }
      }, (err, ipfsd) => {
        if (err) console.error(err)
        ipfsd.stop(() => { defer.resolve() })
      })
    }
  })
  .add('js 512', {
    defer: true,
    fn: function (defer) {
      const f = create({ type: 'js' })
      f.spawn({
        initOptions: { bits: 512 }
      }, (err, ipfsd) => {
        if (err) console.error(err)
        ipfsd.stop(() => { defer.resolve() })
      })
    }
  })
  .add('js disposable', {
    defer: true,
    fn: function (defer) {
      const f = create({ type: 'js' })
      f.spawn({}, (err, ipfsd) => {
        if (err) console.error(err)
        ipfsd.stop(() => { defer.resolve() })
      })
    }
  })
  .on('cycle', function (event) {
    console.log(String(event.target))
  })
  .on('complete', function () {
    console.log('Fastest is ' + this.filter('fastest').map('name'))
  })
  .run()
```

**Comment by mkg20001** [comment]
@hugomrdias The nodes need to be disposabshle nodes and should not have the `bits` option set to any value. I don't know if including ids for all common keys sizes (512, 1024 - 2048 already is added) makes sense, I could add that too if needed

**Comment by hugomrdias** [comment]
that's what i tested with the code above bits = 512 vs disposable and no gains

**Comment by mkg20001** [comment]
Are nodes spawned as disposable nodes by default? Because the code says that `opts.disposable` has null as default https://github.com/ipfs/js-ipfsd-ctl/blob/master/src/ipfsd-daemon.js#L57 but I'm unsure if there is something I missed that changes that

**Comment by hugomrdias** [comment]
yes they are

**Comment by alanshaw** [comment]
Is this a fair test?

The pregenerated keys are 2048 bits but we're comparing against 512. Is there a performance win when JS is set to generate it's own key of 2048 bits?

(btw I know the tests all use 512)

go-ipfs mandates a minimum of 1024 bits. js-ipfs should really do the same...will we get a performance win by using this feature when this happens?

It's worth double checking that the pregenerated keys are defintely being used in your tests above.

**Comment by alanshaw** [comment]
> these changes are for tests only right? and should remove all the overhead of creating keys whatever the size. I can run the bench for 2048 but i think that misses the point of these changes speeding up the tests. Or am i missing something here?

Not at all! I'm just saying you could try with 2048 - that _should_ be a perf win or something really _is_ up.

Anyway, looks as though there's a small issue passing the pregenerated key when working with a daemon.

It _is_ faster with an in process JS IPFS (`{ type: 'proc', exec: require('ipfs') }`):

```console
js 512 x 3.95 ops/sec ±10.30% (25 runs sampled)
js disposable x 4.76 ops/sec ±4.79% (27 runs sampled)
Fastest is js disposable
```

~18% faster

and with 1024:

```console
js 1024 x 2.95 ops/sec ±65.32% (27 runs sampled)
js disposable x 4.57 ops/sec ±4.47% (26 runs sampled)
Fastest is js disposable,js 1024
```

~36% faster

I guess the `--private-key` option isn't being passed correctly to `jsipfs init`?

**Comment by hugomrdias** [comment]
Did further investigation and `bits` weren't even sent correctly to init.

```
js disposable in-proc x 4.19 ops/sec ±35.65% (29 runs sampled)
js 512 in-proc x 4.75 ops/sec ±6.00% (28 runs sampled)
Fastest is js 1024 in-proc,js disposable in-proc
```
```
js disposable in-proc x 4.12 ops/sec ±37.35% (28 runs sampled)
js 1024 in-proc x 2.90 ops/sec ±13.07% (19 runs sampled)
Fastest is js disposable in-proc
```

These are the current results, as you can see 512 vs pregen its a draw. The variation is so big i did further digging into the code and ofc peer-id creation is faster with pregen, using node `perf_hooks` i measured 512 generation between 10 and 50 ms and pregen between 1 and 8 ms. This reveals super small gains when we are talking about taking 6s to spawn a node.

You notice im comparing 512 to pregen and not 1024 to pregen this is because for these are only meant to improve tests speed, and 512 is enough for tests (go is fast enough even with 2048!), if this is not true please explain me why.

The problem of ctl being slow is else where with a much more complicated solution i'll try to start conversations about that in Glasgow.

Having said that, right now the pregen changes bring inconsistent behavior between daemon and in-proc init flow, a huge json file that doubles the bundle size even gziped and on the pro side super small gains in speed.

My feeling right now tends to revert these changes and fix in-proc init options to send bits correctly and default to 512 bits for tests.

**Comment by mkg20001** [comment]
> My feeling right now tends to revert these changes and fix in-proc init options to send bits correctly and default to 512 bits for tests.

If the impact really is so insignificant then maybe it should get dropped
But I think that those pregenerated ids should still exist somewhere, maybe in another module so they are optional. There will always be key-releated tests that need a bunch of keys (and don't need a node)...

> and 512 is enough for tests (go is fast enough even with 2048!)
Could you check if the changes from https://github.com/libp2p/js-libp2p-crypto/pull/128 were already used? If not then that might have been the bottleneck

**Comment by hugomrdias** [comment]
@mkg20001 this was great work and I still think it should exist here, would you be willing to make same changes ?
I would say remove all the bits and disposable conditions and make it simply behind a flag called pregen or something that makes sense and add some tests? I'll figure out the bundle size part

**Comment by mkg20001** [comment]
@hugomrdias

> I would say remove all the bits and disposable conditions and make it simply behind a flag called pregen or something that makes sense and add some tests?

Sounds good. But if the idea below gets implemented we could also make it auto-enable on disposable: true without bits set. Or we could include different keysizes and make it so the user can set `pregen` as well as `bits` to get pregenerated ids for that particular size.

> I'll figure out the bundle size part.

Another idea would be to make it a seperate module that one can simply plug-in:
```js
const IPFSFactory = require('ipfsd-ctl')
const f = IPFSFactory.create({pregen: require('ipfs-pregen-ids')}) // or even just .create(require('ipfs-pregen-ids'))
```
Then we could even make it bigger (include other keysizes) without bothering the users that don't need it.

> Also can you make a script to generate the json file with a size option so we can make more if we need to?

The "script" I currently use is just https://github.com/mkg20001/test-peer-ids.tk with this patch https://ipfs.io/ipfs/QmVZRWjZoqve9UKgng2gymN8a3FQUENgsQaicQ2fWs7kGx applied but I think it shouldn't be hard to write something better with https://github.com/wilk/microjob which I sadly didn't know about when writing https://test-peer-ids.tk

**Comment by mkg20001** [comment]
:tada: I made this module https://github.com/mkg20001/ipfs-pregen-ids

(Note: Has been made at around ~10pm and generate.js isn't working because of https://github.com/wilk/microjob/issues/26 so expect bugs)

**Comment by hugomrdias** [comment]
Sounds like a great plan. 🎉🎉🚀

**Comment by mkg20001** [comment]
:tada: :rocket: https://github.com/mkg20001/ipfs-pregen-ids has now been updated to include tests, bugfixes and more keysizes. Also generate.js works now.

**Comment by mkg20001** [comment]
:tada: https://github.com/ipfs/js-ipfsd-ctl/pull/300

**Comment by hugomrdias** [comment]
im closing this in favor of #300
