### ISSUE TITLE
docs: route-overflow

### ISSUE THREAD

**Issue by mkg20001** [ipfs/js-ipfsd-ctl#296]
Just decided to check out the docs of this repo.

I think there is a bit too much "route" stuff there:
![screenshot](https://user-images.githubusercontent.com/7735145/45831494-cdc93c80-bcff-11e8-91d6-135f9ebfe382.png)

I'm guessing that this is comming from the server part of the client. It would be great if this could be cleaned up somehow.

**Comment by hugomrdias** [comment]
next release will have better docs :) working on it 
thx for the feedback
