### ISSUE TITLE
Make ipfsd-ctl as robust as calling ipfs daemon manually

### ISSUE THREAD

**Issue by olizilla** [ipfs/js-ipfsd-ctl#315]
With go-ipfs@0.4.18, `ipfs daemon` will start up cleanly even if there is an `api` file  or  a `repo.lock` file or both in `$IPFS_HOME`, as happens if daemon process is not shutdown gracefully.

`ifpsd-ctl` will fail with an `ECONNREFUSED` if there  is an `api`  file in the repo. This causes issues for apps written to use  ipfsd-ctl. The command line tool works fine but the  app can't start.

 A user can create the  issue by quickly `ctrl+c`-ing the  deamon from the cli, or from  an os level shutdown that doens't allow time for ifpsd-ctl to shutdown.

It would be super helpful to make ipfsd-ctl as robust as running to unclean  repos  as `ipfs daemon` is,  otherwise apps will implement their own hacks, or just be unreliable.

See: 
- https://github.com/ipfs/js-ipfsd-ctl/issues/226#issuecomment-379041502
- https://github.com/ipfs-shipyard/ipfs-desktop/pull/722#issuecomment-444139824

**Comment by achingbrain** [comment]
Being able to override lock files would solve ipfs/js-ipfs#522 too.

I thought I'd opened an issue somewhere proposing something like:

```console
$ jsipfs daemon
The repo at ~/.jsipfs is locked, type `yolo` to contine or CTRL+C to abort
(y)olo >
```

..but now I can't find it.  Might have just been in my head.
