### ISSUE TITLE
Latest version of `local` is broken

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-ipfsd-ctl#32]
I've just upgraded station, but it seems that `ipfsd.local` and the subsequent `node.startDaemon` are broken. When running on an already initialized state `node.startDaemon` just hangs without ever calling back

**Comment by diasdavid** [comment]
Is this still an issue?

**Comment by diasdavid** [comment]
No longer a issue, I believe. Reopen if necessary
