### ISSUE TITLE
Spawn daemon and args not used if disposable

### ISSUE THREAD

**Issue by vasco-santos** [ipfs/js-ipfsd-ctl#330]
After discussing this issue on [ipfs/interop#60#issuecomment-483207296](https://github.com/ipfs/interop/pull/60#issuecomment-483207296), if we spawn a disposable daemon it will not start automatically. 

In this context, as we need to start it manually, the possible args that we can provide on `spawn` options are not used in `start`. I think that we should merge the `args` that we provide via options in `spawn` with eventual `args` that can be provided through start (https://github.com/ipfs/js-ipfsd-ctl#ipfsdstartflags-callback).

What do you think @hugomrdias ?

**Comment by hugomrdias** [comment]
need to merge this https://github.com/ipfs/js-ipfsd-ctl/pull/308 first
