### ISSUE TITLE
Dont allow api access from any origin by default

### ISSUE THREAD

**Issue by olizilla** [ipfs/js-ipfsd-ctl#333]
The default config for nodes created by ipfsd-ctl allows api access from any origin

https://github.com/ipfs/js-ipfsd-ctl/blob/0ad2e1716f71ffd12e4886e3051a08147230c134/src/defaults/config.json#L2-L4

If people build apps that use this without understanding the risk they could put users at risk of allowing untrusted web-apps full access to their api.

ideally the default would be restrictive, as the deafult go-ipfs config is.

**Comment by lidel** [comment]
I agree. We can't assume ipfsd-ctl will be used in tests, and the default config should be changed to ship without `Access-Control-Allow-Origin: *`. 


Still, we don't want to manually set config in every test suite that relies on ipfsd-ctl. 
Perhaps adding a separate opt-in `test` profile is a way to go?

**Comment by olizilla** [comment]
That would be neat, but js-ipfs doesn't support the `profile` option and go-ipfs doesn't set any [api http headers when that profile is applied](https://github.com/ipfs/go-ipfs-config/blob/687234717fb9e022b469121d33582a5b821ed39d/profile.go#L74-L90), so it'd be suprising to also change the API config block because of that flag.

I think we'd probably want to look at inverting the logic around the `defaultAddrs` flag, which currently removes just the override for the Addresses block, but I think should probably be inverted so that we opt in to test specific overrides with a `useRandomPorts: true` and a `allowApiAccessFromAnyOrigin: true` or similar, which would better describe what the current default config is doing https://github.com/ipfs/js-ipfsd-ctl/blob/412c18f0fae9d003f98752cc0e8ef4e0ea69f0a8/src/defaults/config.json#L1-L19

**Comment by olizilla** [comment]
Proposal:

### `factory.spawn`
- Remove the `defaultAddrs` option. It assume that the module is primarly for testing, and that the user should opt in to get something closer to the default config that you'd get from starting the nodes manually.

### `IPFSFactory.create`
- Add a `defaultConfig` option that takes a valid ipfs config object. The factory instance will deep merge those values with the `config` object passed to `factory.spawn` as it does now, only it is provided by the user, rather than [hardcoded](https://github.com/ipfs/js-ipfsd-ctl/blob/412c18f0fae9d003f98752cc0e8ef4e0ea69f0a8/src/factory-daemon.js#L89-L93)

We could export the current default config on the module, and then in our test code we can deliberately apply it like

```js
const IPFSFactory = require('ipfsd-ctl')
const defaultConfig = IPFSFactory.testConfig
module.exports = IPFSFactory.create({defaultConfig})
```
https://github.com/ipfs/js-ipfs-http-client/blob/master/test/utils/factory.js#L3-L5

**Comment by olizilla** [comment]
@hugomrdias @alanshaw pls can have your thoughts

**Comment by tapaswenipathak** [comment]
Hi folks, Can I work on the ticket?

**Comment by olizilla** [comment]
@tapaswenipathak if you would like to contribute a PR with a fix for this issue that would be great!

@hugomrdias any thoughts on the proposed fix?

**Comment by tapaswenipathak** [comment]
Hey @olizilla: I don't think I understand the proposed fix; per me the CORS should define per implementation the restriction leaving the core generic. 

Do you mean IPFSFactory.create will take input from CLI?

Let me know if you have any finalised approach or leaving the issue for now.

**Comment by lidel** [comment]
@hugomrdias just the record, how is CORS config handled in v1.0.x? 

Was `"Access-Control-Allow-Origin": ["*"]` removed from default contexts?
If so, is it now set by Aegir, only in text contexts?

**Comment by hugomrdias** [comment]
no, now only if you pass `test: true` you will get cors
