### ISSUE TITLE
Command failed with ENOENT: ipfs/src/cli/bin.js daemon... when spawing a js node from a factory

### ISSUE THREAD

**Issue by sebastiendan** [ipfs/js-ipfsd-ctl#471]
Hi,

#458 introduced changes on how the js/go bin are resolved, but Usage on README was not updated, so took me a while before understanding I have to specify the bin path, the same way it's done in /examples.

When testing with:
```
this.node = await factory.spawn({
  type: 'js',
  ipfsBin: require.resolve('ipfs/src/cli/bin.js'),
})
``` 

I get the following error:

```
Command failed with ENOENT: ipfs/src/cli/bin.js daemon --enable-preload false
spawn ipfs/src/cli/bin.js ENOENT 


    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

**Comment by sebastiendan** [comment]
Besides the documentation issue, It seems the problem is coming from my environment: passing the path manually works.

```
this.node = await factory.spawn({
      type: 'js',
      ipfsBin: join(
        __dirname,
        '..',
        '..',
        '..',
        'node_modules/ipfs/src/cli/bin.js'
      ),
    })
```

My context is a NestJS (so NodeJS) app inside an [Nx](https://github.com/nrwl/nx) workspace.
That's my first project with Nx so I'll investigate for this part.

For now `require.resolve` just returns whatever string that is passed to it...

**Comment by hugomrdias** [comment]
readme docs and types were improved to explain this better.
