### ISSUE TITLE
initialized not set after spawning

### ISSUE THREAD

**Issue by hacdias** [ipfs/js-ipfsd-ctl#500]
The `initialized` variable is defined as `false` in the constructor and it is never updated unless we call `init`.

https://github.com/ipfs/js-ipfsd-ctl/blob/f8decb34d8e1ccfdf79e042d98168dd01746aea0/src/ipfsd-daemon.js#L81-L86

I think calling `repoExists` in the constructor would be better to set the `initialized` variable. This way there's no way to check if the repository already existed without checking if the repository exists ourselves.

/cc @hugomrdias

**Comment by hugomrdias** [comment]
repoExists is async can't be called in the contructor, can you explain further your use case ?

**Comment by hacdias** [comment]
Previously, on IPFS Desktop, we were checking if the repository was initialized or not to take certain actions. By updating to 3.x we're changing that logic a bit and checking if the config exists or not so we won't be needing the `initialized` variable to be set right away.

However, for someone that might want to do something depending on whether or not the repository is already initialized or not, they'll need to check if the repository exists by themselves.

Also, `pathExists` can be replaced by `pathExistsSync`. Not sure about the implications of that change though.

I saw you solved the other issue, so thanks :D

**Comment by hugomrdias** [comment]
that only works in node, repoExists is always async in the browsers.

it would be better to expose repoExists than to use `initialized` for this but thats another issue. 

please re-open if you think this needs more discussion
