### ISSUE TITLE
webpack_require(...).path is not a function

### ISSUE THREAD

**Issue by haurx** [ipfs/js-ipfsd-ctl#503]
error:
**TypeError: __webpack_require__(...).path is not a function
      at getIpfsBinPath (webpack:///./src/main/daemon/daemon.js?:141:92)
      at _callee2$ (webpack:///./src/main/daemon/daemon.js?:74:24)**

function getIpfsBinPath () {
  return require('go-ipfs-dep').path().replace('app.asar', 'app.asar.unpacked') 
}

async function cleanup (ipfsd) {
  const log = logger.start('[daemon] cleanup')

  if (!configExists(ipfsd)) {
    cannotConnectDialog(ipfsd.apiAddr)
    throw new Error('cannot connect to api')
  }

  log.info('run: ipfs repo fsck')
  const exec = getIpfsBinPath()

  try {
    execFileSync(exec, ['repo', 'fsck'], {
      env: {
        ...process.env,
        IPFS_PATH: ipfsd.path
      }
    })
    log.end()
  } catch (err) {
    log.fail(err)
  }
}

async function spawn ({ flags, path, keysize }) {
  const ipfsd = await Ctl.createController({
    ipfsHttpModule: require('ipfs-http-client'),
    ipfsBin: getIpfsBinPath(),
    ipfsOptions: {
      repo: path
    },
    remote: false,
    disposable: false,
    test: false,
    args: flags,
  })

**Comment by achingbrain** [comment]
I think you have an old version of `go-ipfs-dep` as a dependency - please use `0.4.23-3` (not `0.4.23`) or `0.5.0`.

**Comment by jacobheun** [comment]
Closing, please reopen if you are still having this problem.
