### ISSUE TITLE
AlreadyInitializedError: cannot re-initialize an initialized node

### ISSUE THREAD

**Issue by aphelionz** [ipfs/js-ipfsd-ctl#505]
Right now I'm trying to wire up https://github.com/orbitdb/orbit-db-test-utils with `js-ipfs@^0.43.0` and `go-ipfs@0.5.0`

Go IPFS is requiring the keys to be 2048 bits or larger, so I added the `init` configuration to the `proc` node like so:

```javascript
module.exports = {
  defaults: {
    type: 'proc',
    test: true,
    disposable: true,
    ipfsModule: require('ipfs'),
    // These don't seem to have any effect
    // init: false,           
    // start: false,
    ipfsOptions: {
      init: {
        bits: 2048
      },
      config: {
        Addresses: {
          API: '/ip4/127.0.0.1/tcp/0',
          Swarm: ['/ip4/0.0.0.0/tcp/0'],
          Gateway: '/ip4/0.0.0.0/tcp/0'
        },
        Bootstrap: []
      }
    }
  },
  overrides: {
    go: {
      test: false,
      ipfsHttpModule: require('ipfs-http-client'),
      ipfsBin: require('go-ipfs-dep').path()
    }
  }
}
```

However, I get this error during the tests when trying to start a `proc` node:

```
  1) swarm workflow
       localSwarm (1): proc:
     AlreadyInitializedError: cannot re-initialize an initialized node
      at Proxy.init (node_modules/ipfs/src/core/components/init.js:340:31)
      at InProc.init (node_modules/ipfsd-ctl/src/ipfsd-in-proc.js:93:20)
      at async Factory.spawn (node_modules/ipfsd-ctl/src/factory.js:141:7)
      at async Promise.all (index 0)
      at async swarm (swarm.js:3:661)
      at async Context.<anonymous> (test/swarm.spec.js:34:21)
```
**Further context:**
1. You can see all my latest code in this branch: https://github.com/orbitdb/orbit-db-test-utils/pull/11
2. Code sandbox reproducing the error: https://codesandbox.io/s/error-reinitialize-c5c9n

cc @hugomrdias

**Comment by aphelionz** [comment]
Looks like this is being addressed here: https://github.com/ipfs/js-ipfs/pull/3013

**Comment by achingbrain** [comment]
You may be able to get a bit further now that https://github.com/ipfs/js-ipfsd-ctl/pull/504 has been merged & released as the key size isn't hard-coded any more so you can remove the `init: { bits: 2048 },` bit of the config, which should stop the `cannot re-initialize an initialized node` (which should be resolved by https://github.com/ipfs/js-ipfs/pull/2762 if I can find some time to get it into shape).

Anyway please try upgrading to `ipfsd-ctl@4.1.0`

**Comment by aphelionz** [comment]
4.1.0 works! I am unblocked.
