### ISSUE TITLE
NULL API fatal error

### ISSUE THREAD

**Issue by rafaelramalho19** [ipfs/js-ipfsd-ctl#556]
## Description:
- When restarting the computer, or some similar use-case where the API is not initialized yet for some reason, ipfsd-ctl throws a fatal error:

```
TypeError: Cannot read property 'pid' of null
    at Timeout._onTimeout (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\ipfsd-ctl\src\ipfsd-daemon.js:242:101)
```

Linked with: https://github.com/ipfs-shipyard/ipfs-desktop/issues/1702

**Comment by achingbrain** [comment]
That code has been refactored recently, can you please try with the latest version?
