### ISSUE TITLE
Electron + electron-builder windows asar

### ISSUE THREAD

**Issue by geolffreym** [ipfs/js-ipfsd-ctl#586]
Hi guys
Having same issue trying package https://github.com/ipfs/notes/issues/256

**Comment by achingbrain** [comment]
What's the issue you're having?

**Comment by geolffreym** [comment]
Think its related to symlink to go-ipfs in windows, now using as peerDependencies and installing with window-elevate look it working for now..

**Comment by achingbrain** [comment]
Glad you figured it out!
