### ISSUE TITLE
Error: 404 on all server endpoints

### ISSUE THREAD

**Issue by denyncrawford** [ipfs/js-ipfsd-ctl#640]
I'm working with electron and trying to implement the controller, I did a very similar thing as in your electron example [here](https://github.com/ipfs/js-ipfsd-ctl/blob/08eb574b895459b8f844973c5025e827bd6936f0/examples/electron-asar/app.js#L25), the controller is not connecting to the server and shows this errors con devtools (ignore vue warn):

![image](https://user-images.githubusercontent.com/28849055/124796195-45a39880-df27-11eb-9e43-97953fc8a9cc.png)

**When opening any endpoint on the browser it shows**:

- **http://127.0.0.1:5001/x**: `{"statusCode":404,"error":"Not Found","message":"Not Found"}`
- **http://127.0.0.1:5002/x**: `{"Message":"Method Not Allowed","Code":1,"Type":"error"}`

**This is my code**:

```JavaScript
const { createServer, createController } = require('ipfsd-ctl')
const ipfsHttpModule = require('ipfs-http-client');
const ipfsBin = require.resolve('ipfs/src/cli.js');

export const getDataNode = async (port) => {
  const server = createServer({
    host: '127.0.0.1',
    port
    } , {
    ipfsHttpModule,
    ipfsBin,
    type: 'js',
    disposable: false
  })

  console.log(await server.start())

  const ipfsd = await createController({
    ipfsHttpModule,
    remote: true,
    type: 'js',
    endpoint: `http://127.0.0.1:${port}`
  })
  console.log(ipfsd);
  return ipfsd.api
};
```

**Comment by yingshaoxo** [comment]
@denyncrawford 

Hi, why did you close this repo?

How do you solve it in the end?

**Comment by denyncrawford** [comment]
> @denyncrawford
> 
> Hi, why did you close this repo?
> 
> How do you solve it in the end?

Please follow this https://github.com/denyncrawford/mismor-main/blob/d145bc1305147781544990ca37df8862063ac65b/src/render/store.js#L18 just create a controller with a client and pass it a binary (jsipfs or ipfs-go), then remember to init and start IPFS before exporting the API.
