### ISSUE TITLE
Enumerate the tests in order to make sure that execa is as robust as subcommandante

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfsd-ctl#95]
As discussed in August 15 js-ipfs sprint meeting. @jbenet please enumerate all the tests you would like to see for: https://github.com/ipfs/js-ipfsd-ctl/pull/89

//cc @jgantunes

**Comment by jbenet** [comment]
@diasdavid no sorry I don't have time for this in the next 2 weeks. If you
want me to this it probably won't get done for a while.

**Comment by jbenet** [comment]
The burden of proof also lies on whoever wants to _change_ the behavior.
Its up to that PR to ensure correctness

**Comment by diasdavid** [comment]
Ok, I'll handle this myself with @jgantunes

**Comment by dignifiedquire** [comment]
I found out the hard way that it isn't :(

**Comment by diasdavid** [comment]
Could you elaborate?

**Comment by diasdavid** [comment]
Nvm, saw the commits on https://github.com/ipfs/js-ipfsd-ctl/pull/140#issuecomment-268774809, closing this one then :)
